private ["_pos","_anim","_chair","_ran","_group","_unit","_dir","_obj","_cor"];
_pos = _this select 0;
_anim = ["Hepler_InjuredNon"]call RETURNRANDOM;
_chair = ["Land_Sleeping_bag_F"]call RETURNRANDOM;
_ran = CIVS1 call RETURNRANDOM;
_group = [[10000,10000,0], CIVILIAN, [_ran],[],[],[0.6,0.9]] call SpawnGroupCustom;
_unit = leader _group;
_dir = random 360;
_cor = ([_pos, getposATL (_this select 1)] call SAOKDIRT);
_pos = [(_pos select 0)+((sin _cor)*1),(_pos select 1)+((cos _cor)*1),(_pos select 2)];
_obj = createVehicle [_chair,_pos, [], 0, "CAN_COLLIDE"]; 
_obj disableCollisionWith _unit; 
_obj setpos _pos;
//_obj setvectorup (surfaceNormal (getposATL _obj));
_obj setdir _dir;
if (lineIntersects [(_obj modelToWorld [0.2,-2.3,0.1]) CALL SAOKATLTOASL,(_obj modelToWorld [0.2,1.3,0.1]) CALL SAOKATLTOASL,_obj]) exitWith {hint "boj";deletevehicle _obj;[]};
_unit setdir (_dir+180);
_group setformdir (_dir+180);
_unit switchmove _anim;
_unit setbehaviour "CARELESS";
_unit disableAI "AUTOTARGET";
_unit disableAI "TARGET";
//_unit disableAI "FSM";
_unit disableAI "MOVE";
//_unit setpos _pos;
//_obj setpos [getposATL _obj select 0,getposATL _obj select 1,(getposATL _obj select 2)-0.2];
_unit setpos (_obj modelToWorld [+0.2,-1,0.1]);
_unit setvariable ["CivNo",1];
[_unit, _obj]