
player action ["lightOn", _this]; 
_this say3d "AlarmCar";
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
_this say3d "AlarmCar";
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
_this say3d "AlarmCar";
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
_this say3d "AlarmCar";
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
_this say3d "AlarmCar";
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
_this say3d "AlarmCar";
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
sleep 0.5;
player action ["lightOn", _this]; 
sleep 0.5;
player action ["lightOff", _this]; 
