private ["_p","_dataW","_center","_radius","_objectType","_holes","_corner1","_corner2","_corner3","_corner4","_walls","_data","_n","_dir","_alN","_f"];
_center = _this select 0;
_radius = _this select 1;
_objectType = _this select 2;
_alN = if (count _this > 4) then {_this select 4} else {0};
_dataW = [];
_holes = 1;
_dir = random 90;
_corner1 = [(_center select 0)+((sin _dir)*_radius),(_center select 1)+((cos _dir)*_radius),0];
_dir = _dir + 90;
_corner2 = [(_center select 0)+((sin _dir)*_radius),(_center select 1)+((cos _dir)*_radius),0];
_dir = _dir + 90;
_corner3 = [(_center select 0)+((sin _dir)*_radius),(_center select 1)+((cos _dir)*_radius),0];
_dir = _dir + 90;
if (_dir > 360) then {_dir = _dir - 360;};
_corner4 = [(_center select 0)+((sin _dir)*_radius),(_center select 1)+((cos _dir)*_radius),0];
_walls = [];
_n = 0;
if (_holes > 0) then {_n = 1; _holes = _holes - 1;};
_p = "FUNKTIO_DrawFenceCV";
if (_objectType in ["Land_Mil_WallBig_4m_F","Land_CncWall4_F","Land_Shoot_House_Wall_Long_F","Land_Razorwire_F"]) then {_p = "FUNKTIO_DrawFenceV";};
_f = missionnamespace getvariable _p;
// _data = [_corner1 ,_corner2,_objectType,0,0] CALL FUNKTIO_DrawFenceCV;
_data = [_corner1 ,_corner2,_objectType,_n,_alN] CALL _f;
_walls append (_data select 0);
_dataW append (_data select 2);
_n = 0;
if (_holes > 0) then {_n = 1; _holes = _holes - 1;};
if (count (_data select 1) > 0 && {(_data select 1) distance _corner2 < 4}) then {_corner2 = + (_data select 1);};
_p = "FUNKTIO_DrawFenceCV";
if (_objectType in ["Land_Mil_WallBig_4m_F","Land_CncWall4_F","Land_Shoot_House_Wall_Long_F","Land_Razorwire_F"]) then {_p = "FUNKTIO_DrawFenceV";};
_f = missionnamespace getvariable _p;
_data = [_corner2 ,_corner3,_objectType,_n,(_alN+(count _dataW))] CALL _f;
_walls append (_data select 0);
_dataW append (_data select 2);

_n = 0;
if (count _this > 3 && {typename (_this select 3) == "STRING"}) then {
_objectType = ["Land_HBarrierWall_corridor_F","Land_Razorwire_F","Land_HBarrier_5_F","Land_HBarrierWall6_F","Land_BagFence_Long_F","Land_BagFence_Long_F","Land_HBarrier_3_F","Land_HBarrierBig_F","Land_HBarrierWall4_F"] call RETURNRANDOM;
if (!isNil"IFENABLED") then {_objectType = ["Land_fort_rampart","Land_fort_bagfence_long","Land_Shoot_House_Wall_Long_F","Land_Mil_WallBig_4m_F","Land_BagFence_Long_F","Land_BagFence_Long_F"] call RETURNRANDOM;};
};
if (_holes > 0) then {_n = 1; _holes = _holes - 1;};
if (count (_data select 1) > 0 && {(_data select 1) distance _corner3 < 4}) then {_corner3 = + (_data select 1);};
_p = "FUNKTIO_DrawFenceCV";
if (_objectType in ["Land_Mil_WallBig_4m_F","Land_CncWall4_F","Land_Shoot_House_Wall_Long_F","Land_Razorwire_F"]) then {_p = "FUNKTIO_DrawFenceV";};
_f = missionnamespace getvariable _p;
_data = [_corner3 ,_corner4,_objectType,_n,(_alN+(count _dataW))] CALL _f;
_walls append (_data select 0);
_dataW append (_data select 2);
_n = 0;
if (_holes > 0) then {_n = 1; _holes = _holes - 1;};
if (count (_data select 1) > 0 && {(_data select 1) distance _corner4 < 4}) then {_corner4 = + (_data select 1);};
_p = "FUNKTIO_DrawFenceCV";
if (_objectType in ["Land_Mil_WallBig_4m_F","Land_CncWall4_F","Land_Shoot_House_Wall_Long_F","Land_Razorwire_F"]) then {_p = "FUNKTIO_DrawFenceV";};
_f = missionnamespace getvariable _p;
_data = [_corner4 ,_corner1,_objectType,_n,(_alN+(count _dataW))] CALL _f;
_walls append (_data select 0);
_dataW append (_data select 2);
//hint format ["laatikko %1",_dataW];
[_walls,_dataW]